/* SPDX-License-Identifier: GPL-3.0-or-later */
package com.chlna6666.tongshihanzi.ui.search;

import android.view.LayoutInflater;import android.view.View;import android.view.ViewGroup;import android.widget.TextView;import androidx.annotation.NonNull;import androidx.recyclerview.widget.DiffUtil;import androidx.recyclerview.widget.ListAdapter;import androidx.recyclerview.widget.RecyclerView;import com.chlna6666.tongshihanzi.R;import com.chlna6666.tongshihanzi.domain.search.SearchResult;
public final class SearchResultAdapter extends ListAdapter<SearchResult,SearchResultAdapter.Holder>{
    public interface Listener{void onOpen(SearchResult item);}private final Listener listener;
    public SearchResultAdapter(Listener listener){super(new DiffUtil.ItemCallback<>(){public boolean areItemsTheSame(@NonNull SearchResult a,@NonNull SearchResult b){return a.getCharacterId()==b.getCharacterId();}public boolean areContentsTheSame(@NonNull SearchResult a,@NonNull SearchResult b){return a.getScore()==b.getScore()&&a.getPinyin().equals(b.getPinyin())&&a.getDefinition().equals(b.getDefinition())&&a.getMatchType().equals(b.getMatchType());}});this.listener=listener;}
    @NonNull @Override public Holder onCreateViewHolder(@NonNull ViewGroup parent,int viewType){return new Holder(LayoutInflater.from(parent.getContext()).inflate(R.layout.item_search_result,parent,false));}
    @Override public void onBindViewHolder(@NonNull Holder holder,int position){holder.bind(getItem(position),listener);}
    static final class Holder extends RecyclerView.ViewHolder{private final TextView character,pinyin,metadata,definition,matchType;Holder(View v){super(v);character=v.findViewById(R.id.character);pinyin=v.findViewById(R.id.pinyin);metadata=v.findViewById(R.id.metadata);definition=v.findViewById(R.id.definition);matchType=v.findViewById(R.id.match_type);}void bind(SearchResult item,Listener listener){character.setText(item.getCharacter());pinyin.setText(item.getPinyin().trim().isEmpty()?"读音待补充":item.getPinyin());metadata.setText("部首："+(item.getRadical().trim().isEmpty()?"—":item.getRadical())+"　"+item.getTotalStrokes()+" 画");definition.setText(item.getDefinition().trim().isEmpty()?"释义数据待补充":item.getDefinition());matchType.setText(item.getMatchType());itemView.setContentDescription(item.getCharacter()+"，"+item.getPinyin()+"，"+item.getTotalStrokes()+"画");itemView.setOnClickListener(v->listener.onOpen(item));}}
}
