/* SPDX-License-Identifier: GPL-3.0-or-later */
package com.chlna6666.tongshihanzi.ui.search;

import android.app.Application;import android.os.Handler;import android.os.Looper;import androidx.annotation.NonNull;import androidx.lifecycle.AndroidViewModel;import androidx.lifecycle.LiveData;import androidx.lifecycle.MutableLiveData;import com.chlna6666.tongshihanzi.data.CharacterRepository;import com.chlna6666.tongshihanzi.data.SearchRepository;import com.chlna6666.tongshihanzi.data.user.UserRepository;import com.chlna6666.tongshihanzi.domain.search.SearchMode;import com.chlna6666.tongshihanzi.domain.search.SearchResult;import java.util.Collections;import java.util.List;import java.util.concurrent.atomic.AtomicInteger;
public final class SearchViewModel extends AndroidViewModel{
    private final SearchRepository searchRepository;private final CharacterRepository characterRepository;private final UserRepository userRepository;private final Handler handler=new Handler(Looper.getMainLooper());private final AtomicInteger generation=new AtomicInteger();private final MutableLiveData<List<SearchResult>> results=new MutableLiveData<>(Collections.emptyList());private final MutableLiveData<Boolean> loading=new MutableLiveData<>(true);private final MutableLiveData<String> error=new MutableLiveData<>();private String query="";private SearchMode mode=SearchMode.AUTO;private Runnable pending;
    public SearchViewModel(@NonNull Application app){super(app);searchRepository=new SearchRepository(app);characterRepository=new CharacterRepository(app);userRepository=new UserRepository(app);loadCommon();}
    public LiveData<List<SearchResult>> results(){return results;}public LiveData<Boolean> loading(){return loading;}public LiveData<String> error(){return error;}public String query(){return query;}
    public void setQuery(String value){query=value==null?"":value;scheduleSearch();}public void setMode(SearchMode value){mode=value==null?SearchMode.AUTO:value;scheduleSearch();}public void searchNow(){if(pending!=null)handler.removeCallbacks(pending);runSearch();}public void recordOpen(SearchResult result){userRepository.saveHistory(query.trim().isEmpty()?result.getCharacter():query,result.getCharacterId());}
    private void scheduleSearch(){if(pending!=null)handler.removeCallbacks(pending);pending=this::runSearch;handler.postDelayed(pending,120L);}private void runSearch(){int request=generation.incrementAndGet();String current=query.trim();if(current.isEmpty()){loadCommon();return;}loading.setValue(true);error.setValue(null);searchRepository.search(current,mode,value->{if(request==generation.get()){results.postValue(value);loading.postValue(false);}},t->{if(request==generation.get()){error.postValue(t.getMessage()==null?"查询失败":t.getMessage());results.postValue(Collections.emptyList());loading.postValue(false);}});}private void loadCommon(){int request=generation.incrementAndGet();loading.setValue(true);characterRepository.common(20,value->{if(request==generation.get()){results.postValue(value);loading.postValue(false);}});}
}
