/* SPDX-License-Identifier: GPL-3.0-or-later */
package com.chlna.tongshihanzi.ui.favorites;

import android.app.Application;import androidx.annotation.NonNull;import androidx.lifecycle.AndroidViewModel;import androidx.lifecycle.LiveData;import androidx.lifecycle.MutableLiveData;import com.chlna.tongshihanzi.data.CharacterRepository;import com.chlna.tongshihanzi.data.user.SearchHistoryEntity;import com.chlna.tongshihanzi.data.user.UserRepository;import com.chlna.tongshihanzi.domain.search.SearchResult;import java.util.Collections;import java.util.ArrayList;import java.util.HashMap;import java.util.List;import java.util.Map;import java.util.stream.Collectors;
public final class FavoritesViewModel extends AndroidViewModel{
    private final CharacterRepository characters;private final UserRepository users;private final MutableLiveData<List<SearchResult>> items=new MutableLiveData<>(Collections.emptyList());
    public FavoritesViewModel(@NonNull Application app){super(app);characters=new CharacterRepository(app);users=new UserRepository(app);}public LiveData<List<SearchResult>> items(){return items;}public void loadFavorites(){users.favoriteIds(ids->characters.rowsByIds(ids,values->items.postValue(order(values,ids,"收藏"))));}
    public void loadHistory(){users.history(history->{List<Integer> ids=history.stream().map(v->v.characterId).filter(v->v>0).distinct().collect(Collectors.toList());characters.rowsByIds(ids,values->{Map<Integer,String> queries=new HashMap<>();for(SearchHistoryEntity item:history)queries.putIfAbsent(item.characterId,item.query);List<SearchResult> ordered=order(values,ids,"最近查询"),labeled=new ArrayList<>();for(SearchResult value:ordered){String q=queries.get(value.getCharacterId());labeled.add(new SearchResult(value.getCharacterId(),value.getCharacter(),value.getPinyin(),value.getRadical(),value.getTotalStrokes(),value.getDefinition(),q==null?"最近查询":"查询："+q,0));}items.postValue(labeled);});});}
    private static List<SearchResult> order(List<SearchResult> values,List<Integer> ids,String type){Map<Integer,SearchResult> byId=new HashMap<>();for(SearchResult v:values)byId.put(v.getCharacterId(),v);List<SearchResult> out=new ArrayList<>();for(Integer id:ids){SearchResult v=byId.get(id);if(v!=null)out.add(new SearchResult(v.getCharacterId(),v.getCharacter(),v.getPinyin(),v.getRadical(),v.getTotalStrokes(),v.getDefinition(),type,0));}return out;}
}
