plugins {
    id 'java'
    id 'application'
}

group = 'com.chlna.tongshihanzi'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = 'com.chlna.tongshihanzi.builder.DictionaryValidator'
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.13.4'
}

test {
    useJUnitPlatform()
}
